version: "3.9"
networks:
  celebritree_network:
    driver: bridge
services:
  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - client:/usr/share/nginx/client
      - blog:/usr/share/nginx/blog
      - ./blog/images:/usr/share/nginx/blog/images
  client:
    build: client
    volumes:
      - client:/app/build
    env_file:
      - ./.env
  blog:
    build: blog
    volumes:
      - blog:/app/dist
  server:
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  client:
  blog:


