version: "3.9"
networks:
  celebritree_network:
    driver: bridge
services:
  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  client:
    build: ./client
    volumes:
    - client:/app/build
  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
    - server:/app/build
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo

      
