version: "3.9"
networks:
  celebritree_network:
    driver: bridge
services:
  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - client:/usr/share/nginx/client
      - blog:/usr/share/nginx/blog
  client:
    build: client
    volumes:
    - client:/app/build
  blog:
    build: blog
    volumes:
    - blog:/app/dist
  server:
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
volumes:
  client:
  blog:      

