version: "3.9"
networks:
  celebritree_network:
    driver: bridge
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./blog/images:/usr/share/nginx/blog/dist/images
    volumes_from:
      - client
      - blog
  client:
    build: client
    volumes:
      - /usr/share/nginx/client/build
  blog:
    build: blog
    volumes:
      - /usr/share/nginx/blog/dist
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  mongodb_data: