FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY celebritree.in.key /etc/ssl/celebritree.in.key
COPY celebritree.in.pem /etc/ssl/celebritree.in.pem
COPY client.certificate.pem /etc/ssl/client.certificate.pem